
// ********RoostGPT********
/*
Test generated by RoostGPT for test javaspring-unit-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test javaspring-unit-test using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=equals_15c51dceab
ROOST_METHOD_SIG_HASH=equals_ded257778a


*/

// ********RoostGPT********

package org.agoncal.application.petstore.model;

import org.junit.Before;
import org.junit.Test;
import org.junit.experimental.categories.Category;
import org.junit.Assert;
import org.agoncal.application.petstore.constraints.Email;
import org.agoncal.application.petstore.constraints.Login;
import javax.persistence.*;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Past;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.Serializable;
import java.security.MessageDigest;
import java.util.*;

public class CustomerEqualsTest {

	private Customer customer1;

	private Customer customer2;

	private Customer customer3;

	private Address address;

	@Before
	public void setUp() {
		address = new Address("123 Main St", "New York", "99999", new Country());
		customer1 = new Customer("John", "Doe", "jdoe", "password", "jdoe@example.com", address);
		customer2 = new Customer("Jane", "Doe", "jdoe", "password", "jdoe@example.com", address);
		customer3 = new Customer("Bob", "Smith", "bsmith", "password", "bsmith@example.com", address);
	}

	@Test
	@Category(Categories.valid.class)
	public void testEqualsSameInstance() {
		Assert.assertTrue(customer1.equals(customer1));
	}

	@Test
	@Category(Categories.valid.class)
	public void testEqualsDifferentInstancesSameLogin() {
		Assert.assertTrue(customer1.equals(customer2));
	}

	@Test
	@Category(Categories.invalid.class)
	public void testEqualsDifferentLogins() {
		Assert.assertFalse(customer1.equals(customer3));
	}

	@Test
	@Category(Categories.invalid.class)
	public void testEqualsNull() {
		Assert.assertFalse(customer1.equals(null));
	}

	@Test
	@Category(Categories.invalid.class)
	public void testEqualsDifferentClass() {
		Assert.assertFalse(customer1.equals(new Object()));
	}

}